[package]
name = "template-tauri"
version = "0.7.0"

[package.description]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.publish]
workspace = true

[build-dependencies.tauri-build]
version = "2.0.0-beta.10"
features = []

[dependencies]
anyhow = "1.0.81"
serde_json = "1.0.114"
tauri-plugin-manatsu = "0.6.0"
tauri-plugin-window-state = "2.0.0-beta.3"
thiserror = "1.0.58"

[dependencies.tauri]
version = "2.0.0-beta.13"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.sea-orm]
version = "0.12.15"
features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
]

[dependencies.tokio]
version = "1.36.0"
features = [
    "macros",
    "rt-multi-thread",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
