[package]
name = "tauri-template"
version = "0.11.0"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[build-dependencies.tauri-build]
version = "2.0.0-beta.15"
features = []

[dependencies]
anyhow = "1.0.83"
chrono = "0.4.38"
futures = "0.3.30"
futures-concurrency = "7.6.0"
itertools = "0.12.1"
rayon = "1.10.0"
serde_json = "1.0.117"
tauri-plugin-manatsu = "0.10.5"
thiserror = "1.0.60"

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.serde]
version = "1.0.201"
features = ["derive"]

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.19"
features = ["protocol-asset"]

[dependencies.tauri-plugin-http]
version = "2.0.0-beta.7"
features = ["rustls-tls"]

[dependencies.tokio]
version = "1.37.0"
features = ["full"]

[dependencies.tracing]
version = "0.1.40"
features = ["release_max_level_off"]

[dependencies.tracing-appender]
version = "0.2.3"
features = ["parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["chrono", "env-filter", "fmt", "parking_lot", "registry"]

[features]
custom-protocol = ["tauri/custom-protocol"]
