[package]
name = "template-tauri"
version = "0.4.6"

[package.description]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true

[package.publish]
workspace = true

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
serde_json = "1.0.114"
tauri-plugin-manatsu = "0.4.1"
tauri-plugin-window-state = "0.1.0"
thiserror = "1.0.57"

[dependencies.tauri]
version = "1.6.0"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
