[package]
name = "template-tauri"
version = "0.9.4"
description = "A Manatsu App"
authors = ["You <email@example.com>"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77"
publish = false

[build-dependencies.tauri-build]
version = "2.0.0-beta.11"
features = []

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.37"
futures = "0.3.30"
itertools = "0.12.1"
serde_json = "1.0.115"
tauri-plugin-manatsu = "0.7.5"
tauri-plugin-window-state = "2.0.0-beta.4"
thiserror = "1.0.58"

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.14"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.tokio]
version = "1.37.0"
features = ["macros", "rt-multi-thread"]

[features]
custom-protocol = ["tauri/custom-protocol"]
