[package]
name = "template-tauri"
version = "0.5.11"

[package.description]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.publish]
workspace = true

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
anyhow = "1.0.80"
serde_json = "1.0.114"
tauri-plugin-manatsu = "0.4.19"
tauri-plugin-window-state = "0.1.0"
thiserror = "1.0.57"

[dependencies.tauri]
version = "1.6.1"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.sea-orm]
version = "0.12.14"
features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
]

[dependencies.tokio]
version = "1.36.0"
features = [
    "macros",
    "rt-multi-thread",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
