[package]
name = "tauri-template"
version = "0.10.3"
description = "My Tauri app"
authors = ["You <email@example.com>"]
license = "MIT"
repository = ""
edition = "2021"
rust-version = "1.77"
publish = false

[build-dependencies.tauri-build]
version = "2.0.0-beta.12"
features = []

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
futures = "0.3.30"
itertools = "0.12.1"
serde_json = "1.0.115"
tauri-plugin-manatsu = "0.9.7"
tauri-plugin-window-state = "2.0.0-beta.4"
thiserror = "1.0.58"

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.15"
features = []

[dependencies.tauri-plugin-http]
version = "2.0.0-beta.4"
features = ["rustls-tls"]

[dependencies.tokio]
version = "1.37.0"
features = ["full"]

[features]
custom-protocol = ["tauri/custom-protocol"]
