[package]
name = "template-tauri"
version = "0.1.20"
description = "A Manatsu App"
authors = ["You <email@example.com>"]
license = ""
repository = ""
edition = "2021"

[build-dependencies.tauri-build]
version = "1.5"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-manatsu = "0.1"

[dependencies.tauri]
version = "1.5"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
